---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Luciatech Dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false
#footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Luciatech Homepage"
  icon: "fa fa-grin"
  content: "This page holds links and content for all things HomeLab / HomeOffice ! <br />"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Youtube"
    icon: "fab fa-youtube"
    url: "https://youtube.com"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
    target: "_blank"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
  - name: "news.com.au"
    icon: "fas fa-newspaper"
    url: "https://www.news.com.au"
    target: "_blank" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Infrastucture"
    icon: "fas fa-server"
    items:
      - name: "Proxmox"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/proxmox.png"
        subtitle: "Proxmox Server Cluster"
        tag: "infra"
        url: "https://proxmox.luciatech.co:8006"
        target: "_blank" # optional html a tag target attribute
      - name: "Rancher"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/rancher.png"
        subtitle: "Rancher Cluster Mgmt"
        tag: "infra"
        url: "https://rancher.luciatech.co"
        target: "_blank" # optional html a tag target attribute
      - name: "UISP"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/unifi.png"
        subtitle: "UISP Unifi Cloud Infrastructure Mgmt"
        tag: "infra"
        url: "https://uisp.luciatech.co/nms/dashboard"
        target: "_blank" # optional html a tag target attribute
      - name: "BIGIP"                                                                                                                          
        logo: "https://github.com/NX211/homer-icons/raw/master/png/ariang.png"                                                                 
        subtitle: "BIGIP Mgmt"                                                                                      
        tag: "infra"                                                                                                                          
        url: "https://bigip.luciatech.co"                                                                                        
        target: "_blank" # optional html a tag target attribute
      - name: "EdgeOS"                                                                                                                         
        logo: "https://github.com/NX211/homer-icons/raw/master/png/unifi.png"                                                                 
        subtitle: "EdgeOS Mgmt"                                                                                                                
        tag: "infra"                                                                                                                          
        url: "https://edgeos.luciatech.co"                                                                                                          
        target: "_blank" # optional html a tag target attribute 
  - name: "Applications"
    icon: "fas fa-code-branch"
    items:
      - name: "Gitlab Luciatech"
        #logo: "assets/tools/sample.png"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/gitlab.png"
        subtitle: "Luciatech Cloud Gitlab"
        tag: "app"
        url: "https://gitlab.com/luciatech"
        target: "_blank" # optional html a tag target attribute
      - name: "AdGuardHome"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/adguardhome.png"
        subtitle: "Home AdGuard"
        tag: "app"
        url: "http://adguard.luciatech.co:8080"
        target: "_blank" # optional html a tag target attribute
      - name: "ArgoHome"                                                                                                                   
        logo: "https://github.com/NX211/homer-icons/raw/master/png/argocd.png"                                                           
        subtitle: "Home Argo"                                                                                                              
        tag: "app"                                                                                                                            
        url: "http://argo.luciatech.co"                                                                                                        
        target: "_blank" # optional html a tag target attribute
      - name: "LongHorn"                                                                                                                   
        logo: "https://github.com/NX211/homer-icons/raw/master/png/longhorn.png"                                                           
        subtitle: "Home LongHorn"                                                                                                              
        tag: "app"                                                                                                                            
        url: "http://longhorn.luciatech.co"                                                                                                        
        target: "_blank" # optional html a tag target attribute
  - name: "Home Automation / IoT"
    icon: "fas fa-house-user"
    items:
      - name: "HomeAssistant"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/home-assistant.png"
        subtitle: "Home Assistant"
        tag: "iot"
        url: "http://hass.luciatech.co:8123"
        target: "_blank" # optional html a tag target attribute
      - name: "XmasLightsController"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/esphome.png"
        subtitle: "Xmas House Lights Controller"
        tag: "iot"
        url: "http://esphome.luciatech.co"
        target: "_blank" # optional html a tag target attribute
      - name: "Hubitat"
        logo: "https://github.com/NX211/homer-icons/raw/master/png/hubitat.png"
        subtitle: "Home Hubitat"
        tag: "iot"
        url: "http://hubitat.luciatech.co"
        target: "_blank" # optional html a tag target attribute
